### ISSUE TITLE
Error parsing PDFTK output

### ISSUE THREAD

**Issue by khalidjaz** [blambeau/pdf-toolkit#2]
my_pdf = PDF::Toolkit.open("#{Rails.root}/public#{pdf}")

it was working fine on my linux system but now it's raising this error on my MAC OS

**Comment by blambeau** [comment]
What error exactly? "Error parsing..."? Could you provide the .pdf file?

**Comment by khalidjaz** [comment]
It's an issue with the pdftk version I was able to solve the problem by downgrading to pdftk 1.44
